### ISSUE TITLE
Parameter to adjust starting LED

### ISSUE THREAD

**Issue by BlackCatPeanut** [markusressel/ESPHome-Analog-Clock#3]
FEATURE REQUEST: 

Firstly, thanks for the project. I've been using Tasmota then WLED and now ESPHome for this use case. I really like leveraging the extensibility of ESPHome to have temp/humidity and bluetooth proxy on the same board...

One thing I haven't figured out yet is how to adjust the starting LED for the clock - essentially shifting the 12 o'clock around the clock so it can adjust to my specific mounting position. I have my 12 o'clock in the middle of the strip (LED 30) as I wanted the 30 minute location to be where my power cable comes out so it comes out the bottom without impacting the LED strip.

I'm having a play around with the code myself but thought I'd raise it as a useful feature to have under the "globals" section. Will let you know if I figure this out or need some guidance. I'm thinking of some sort of time adjustment based on the pin which is entered...see how it goes...

**Comment by markusressel** [comment]
Hey @BlackCatPeanut!

Thx for the suggestion, it should be possible to add this feature by adding an offset to all of the index values used in the code. Messing with the time might not be the best idea because it will make debugging very unintuitive.

Not sure if I get the time but if so I will let you know :)

**Comment by BlackCatPeanut** [comment]
I've had a playaround and have added the number component to capture the desired offset position. Unfortunately there is no restore as its a lambda so you can accept updates from HA. To keep it, the initial value needs to be set...

I tried to get the value into the lambda but cannot follow the indices code:

`substitutions:
  num_leds: "60"
  
esphome:
  name: clock-living-room
  on_boot:
    # set "loading" effect while initializing
    priority: 500.0
    then:
    # enable clock effect after boot
      - light.turn_on: 
          id: light_ring
          brightness: 100%
          effect: Sync
          red: 0%
          blue: 0%
          green: 0%

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
  password: !secret esphome_password

ota:
  password: !secret esphome_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.20.21
    gateway: 192.168.20.1
    subnet: 255.255.255.0
    dns1: 192.168.20.20

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Clock Living Room Fallback AP"
    password: !secret esphome_password

captive_portal:
    
globals:
  - id: clock_brightness
    type: int
    restore_value: yes
    initial_value: '255'

  - id: clock_indicators_enabled
    type: bool
    restore_value: yes
    initial_value: 'true'

  - id: clock_seconds_enabled
    type: bool
    restore_value: yes
    initial_value: 'true'

  - id: wide_hour_hand_enabled
    type: bool
    restore_value: yes
    initial_value: 'false'

  - id: offset_LED_position
    type: int
    restore_value: false

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Paris
    on_time_sync:
      then:
        - light.turn_on:
            id: light_ring
            effect: Clock

switch:
  - platform: template
    name: "Clock Indicators"
    icon: mdi:progress-clock
    lambda: !lambda |-
      return id(clock_indicators_enabled);
    turn_on_action:
      globals.set:
        id: clock_indicators_enabled
        value: 'true'
    turn_off_action: 
      globals.set:
        id: clock_indicators_enabled
        value: 'false'

  - platform: template
    name: "Clock Seconds"
    icon: mdi:update
    lambda: !lambda |-
      return id(clock_seconds_enabled);
    turn_on_action:
      globals.set:
        id: clock_seconds_enabled
        value: 'true'
    turn_off_action:
      globals.set:
        id: clock_seconds_enabled
        value: 'false'

  - platform: template
    name: "Wide Hour Hand"
    icon: mdi:clock-plus-outline
    lambda: !lambda |-
      return id(wide_hour_hand_enabled);
    turn_on_action:
      globals.set:
        id: wide_hour_hand_enabled
        value: 'true'
    turn_off_action:
      globals.set:
        id: wide_hour_hand_enabled
        value: 'false'

number: # Input number to set position but for permanent setting adjust initial value
  - platform: template
    name: "LED position offset"
    icon: mdi:counter
    min_value: "1"
    max_value: "${num_leds}"
    step: "1"
    initial_value: '30' # Update value to to restore after boot as Lambda updates from HA cannot be restored from Flash 
    set_action:
      then:
        - globals.set:
            id: offset_LED_position
            value: !lambda return x;

light:
  - id: light_ring
    internal: False
    platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: GPIO32
    num_leds: "${num_leds}"
    method: esp32_i2s
    name: "Living Room Clock"
    color_correct: [50%, 50%, 50%]
    effects:
      - addressable_lambda:
          name: "Clock"
          update_interval: 32ms
          lambda: |-
            static boolean initialized;
            static Color clock_ring_colors [${num_leds}];
            if (initialized == false) {
              std::fill_n(clock_ring_colors, it.size(), Color::BLACK);
              initialized = true;
            }
            auto time = id(sntp_time).now();
            if (!time.is_valid()) {
              return;
            }
            int offset = (int) id(offset_LED_position); #Read offset value in lambda
            // calculate led indices
            int second_idx = (int) (time.second * (it.size() / 60));
            int minute_idx = (int) (time.minute * (it.size() / 60));
            // this idx would "jump" in big steps
            int hour_idx = (int) ((time.hour % 12) * (it.size() / 12));
            // this moves one led at a time
            int hour_inc_min_idx = hour_idx + (int) (((float) time.minute / 12) * (it.size() / 60));
            // the hour hand may be bigger than one led, so we use an array for that
            std::vector<int> hour_idx_vector;
            if (id(wide_hour_hand_enabled)) {
              hour_idx_vector.push_back((hour_inc_min_idx - 1 + it.size()) % (it.size()));
              hour_idx_vector.push_back(hour_inc_min_idx);
              hour_idx_vector.push_back((hour_inc_min_idx + 1) % it.size());
            } else {
              hour_idx_vector.push_back(hour_inc_min_idx);
            }
            // fade out old colors
            for (int i = 0; i < it.size(); i++) {
              Color old_color = clock_ring_colors[i];
              int percentage = 2;
              int red = old_color.red;
              int red_sub = std::max(1, (int) ((red / 100.0) * percentage));
              int green = old_color.green;
              int green_sub = std::max(1, (int) ((green / 100.0) * percentage));
              int blue = old_color.blue;
              int blue_sub = std::max(1, (int) ((blue / 100.0) * percentage));
              if (red <= red_sub) { red = 0; } else { red -= red_sub; }
              if (green <= green_sub) { green = 0; } else { green -= green_sub; }
              if (blue <= blue_sub) { blue = 0; } else { blue -= blue_sub; }
              Color new_color = Color(red, green, blue, 0);
              clock_ring_colors[i] = new_color;
            }
            int indicator_brightness = id(clock_brightness) / 3;
            Color indicator_color = Color(indicator_brightness, indicator_brightness, indicator_brightness);
            // set base colors
            Color hour_color = Color(0, 0, id(clock_brightness));
            Color minute_color = Color(0, id(clock_brightness), 0);
            Color second_color = Color(id(clock_brightness), 0, 0);
            if (!id(clock_seconds_enabled)) {
              second_color = Color::BLACK;
            }
            // merge colors if they overlap
            // if minute idx inside hour idx range
            if (std::find(std::begin(hour_idx_vector), std::end(hour_idx_vector), minute_idx) != std::end(hour_idx_vector)) {
              minute_color += hour_color;
            }
            if (second_idx == minute_idx) {
              minute_color += second_color;
              second_color = minute_color;
            } else if (std::find(std::begin(hour_idx_vector), std::end(hour_idx_vector), second_idx) != std::end(hour_idx_vector)) {
              second_color += hour_color;
            }
            
            // === set colors from bottom to top
            // indicators
            if (id(clock_indicators_enabled)) {
              for (int i = 0; i < it.size(); i += (int) ((float) it.size() / 12)) {
                clock_ring_colors[i] = indicator_color;
              }
            }
            // hours
            for (int i = 0; i < hour_idx_vector.size(); i++) {
              clock_ring_colors[hour_idx_vector[i]] = hour_color;
            }
            // minutes
            clock_ring_colors[minute_idx] = minute_color;
            // seconds
            if (id(clock_seconds_enabled)) {
              clock_ring_colors[second_idx] = second_color;
            }
            // apply colors to light
            for (int i = 0; i < it.size(); i++) {
              it[i] = clock_ring_colors[i];
            }
      - addressable_scan:
          name: Sync
          move_interval: 100ms
          scan_width: 1
      - addressable_rainbow:
          name: "Rainbow Spinner"
          speed: 8
          width: "${num_leds}"
      - addressable_rainbow:
          name: "Rainbow Fader"
          speed: 3
          width: "${num_leds}"
      - random:
          name: "Random Slow"
          transition_length: 30s
          update_interval: 30s

# DHT11 Sensor:

#sensor:
#  - platform: dht
#    pin: GPIO2
#    temperature:
#      name: "Living Room Temperature"
#    humidity:
#      name: "Living Room Humidity"
#    update_interval: 60s

**Comment by BlackCatPeanut** [comment]
Tried to pull the offset value into the Lambda but I don't think my understanding of the indices is correct:

`effects:
      - addressable_lambda:
          name: "Clock"
          update_interval: 32ms
          lambda: |-
            static boolean initialized;
            static Color clock_ring_colors [${num_leds}];
            if (initialized == false) {
              std::fill_n(clock_ring_colors, it.size(), Color::BLACK);
              initialized = true;
            }
            auto time = id(sntp_time).now();
            if (!time.is_valid()) {
              return;
            }
            int offset = id(offset_LED_position);
            // calculate led indices
            int second_idx = (int) ((time.second * (it.size() / 60 + offset)));
            int minute_idx = (int) ((time.minute * (it.size() / 60 + offset)));
            // this idx would "jump" in big steps
            int hour_idx = (int) (((time.hour % 12) * (it.size() / 12 + offset)));
            // this moves one led at a time
            int hour_inc_min_idx = hour_idx + (int) (((float) time.minute / 12) * (it.size() / 60));
            // the hour hand may be bigger than one led, so we use an array for that
            std::vector<int> hour_idx_vector;
            if (id(wide_hour_hand_enabled)) {
              hour_idx_vector.push_back((hour_inc_min_idx - 1 + it.size()) % (it.size()));
              hour_idx_vector.push_back(hour_inc_min_idx);
              hour_idx_vector.push_back((hour_inc_min_idx + 1) % it.size());
            } else {
              hour_idx_vector.push_back(hour_inc_min_idx);
            }
            // fade out old colors
            for (int i = 0; i < it.size(); i++) {
              Color old_color = clock_ring_colors[i];
              int percentage = 2;
              int red = old_color.red;
              int red_sub = std::max(1, (int) ((red / 100.0) * percentage));
              int green = old_color.green;
              int green_sub = std::max(1, (int) ((green / 100.0) * percentage));
              int blue = old_color.blue;
              int blue_sub = std::max(1, (int) ((blue / 100.0) * percentage));
              if (red <= red_sub) { red = 0; } else { red -= red_sub; }
              if (green <= green_sub) { green = 0; } else { green -= green_sub; }
              if (blue <= blue_sub) { blue = 0; } else { blue -= blue_sub; }
              Color new_color = Color(red, green, blue, 0);
              clock_ring_colors[i] = new_color;
            }
            int indicator_brightness = id(clock_brightness) / 3;
            Color indicator_color = Color(indicator_brightness, indicator_brightness, indicator_brightness);
            // set base colors
            Color hour_color = Color(0, 0, id(clock_brightness));
            Color minute_color = Color(0, id(clock_brightness), 0);
            Color second_color = Color(id(clock_brightness), 0, 0);
            if (!id(clock_seconds_enabled)) {
              second_color = Color::BLACK;
            }
            // merge colors if they overlap
            // if minute idx inside hour idx range
            if (std::find(std::begin(hour_idx_vector), std::end(hour_idx_vector), minute_idx) != std::end(hour_idx_vector)) {
              minute_color += hour_color;
            }
            if (second_idx == minute_idx) {
              minute_color += second_color;
              second_color = minute_color;
            } else if (std::find(std::begin(hour_idx_vector), std::end(hour_idx_vector), second_idx) != std::end(hour_idx_vector)) {
              second_color += hour_color;
            }
            
            // === set colors from bottom to top
            // indicators
            if (id(clock_indicators_enabled)) {
              for (int i = 0; i < it.size(); i += (int) ((float) it.size() / 12)) {
                clock_ring_colors[i] = indicator_color;
              }
            }
            // hours
            for (int i = 0; i < hour_idx_vector.size(); i++) {
              clock_ring_colors[hour_idx_vector[i]] = hour_color;
            }
            // minutes
            clock_ring_colors[minute_idx] = minute_color;
            // seconds
            if (id(clock_seconds_enabled)) {
              clock_ring_colors[second_idx] = second_color;
            }
            // apply colors to light
            for (int i = 0; i < it.size(); i++) {
              it[i] = clock_ring_colors[i];
            }`

**Comment by BlackCatPeanut** [comment]
Further attempts to integrate the offset into the lambda - I think it needs two offsets - one for seconds & minutes (sec_min_offset) and another for hour (hour_offset)...
```
lambda: |-
            static boolean initialized;
            static Color clock_ring_colors [${num_leds}];
            if (initialized == false) {
              std::fill_n(clock_ring_colors, it.size(), Color::BLACK);
              initialized = true;
            }
            auto time = id(sntp_time).now();
            if (!time.is_valid()) {
              return;
            }
            int sec_min_offset = id(offset_LED_position);
            int hour_offset = (sec_min_offset / 5);
            // calculate led indices
            int second_idx = (int) ((time.second * (it.size() / 60 + sec_min_offset)));
            int minute_idx = (int) ((time.minute * (it.size() / 60 + sec_and_min_offset)));
            // this idx would "jump" in big steps
            int hour_idx = (int) (((time.hour % 12) * (it.size() / 12 + hour_offset)));
            // this moves one led at a time
            int hour_inc_min_idx = hour_idx + (int) (((float) time.minute / 12) * (it.size() / 60));
            // the hour hand may be bigger than one led, so we use an array for that
            std::vector<int> hour_idx_vector;
            if (id(wide_hour_hand_enabled)) {
              hour_idx_vector.push_back((hour_inc_min_idx - 1 + it.size()) % (it.size()));
              hour_idx_vector.push_back(hour_inc_min_idx);
              hour_idx_vector.push_back((hour_inc_min_idx + 1) % it.size());
            } else {
              hour_idx_vector.push_back(hour_inc_min_idx);
            }
            // fade out old colors
            for (int i = 0; i < it.size(); i++) {
              Color old_color = clock_ring_colors[i];
              int percentage = 2;
              int red = old_color.red;
              int red_sub = std::max(1, (int) ((red / 100.0) * percentage));
              int green = old_color.green;
              int green_sub = std::max(1, (int) ((green / 100.0) * percentage));
              int blue = old_color.blue;
              int blue_sub = std::max(1, (int) ((blue / 100.0) * percentage));
              if (red <= red_sub) { red = 0; } else { red -= red_sub; }
              if (green <= green_sub) { green = 0; } else { green -= green_sub; }
              if (blue <= blue_sub) { blue = 0; } else { blue -= blue_sub; }
              Color new_color = Color(red, green, blue, 0);
              clock_ring_colors[i] = new_color;
            }
            int indicator_brightness = id(clock_brightness) / 3;
            Color indicator_color = Color(indicator_brightness, indicator_brightness, indicator_brightness);
            // set base colors
            Color hour_color = Color(0, 0, id(clock_brightness));
            Color minute_color = Color(0, id(clock_brightness), 0);
            Color second_color = Color(id(clock_brightness), 0, 0);
            if (!id(clock_seconds_enabled)) {
              second_color = Color::BLACK;
            }
            // merge colors if they overlap
            // if minute idx inside hour idx range
            if (std::find(std::begin(hour_idx_vector), std::end(hour_idx_vector), minute_idx) != std::end(hour_idx_vector)) {
              minute_color += hour_color;
            }
            if (second_idx == minute_idx) {
              minute_color += second_color;
              second_color = minute_color;
            } else if (std::find(std::begin(hour_idx_vector), std::end(hour_idx_vector), second_idx) != std::end(hour_idx_vector)) {
              second_color += hour_color;
            }
            
            // === set colors from bottom to top
            // indicators
            if (id(clock_indicators_enabled)) {
              for (int i = 0; i < it.size(); i += (int) ((float) it.size() / 12)) {
                clock_ring_colors[i] = indicator_color;
              }
            }
            // hours
            for (int i = 0; i < hour_idx_vector.size(); i++) {
              clock_ring_colors[hour_idx_vector[i]] = hour_color;
            }
            // minutes
            clock_ring_colors[minute_idx] = minute_color;
            // seconds
            if (id(clock_seconds_enabled)) {
              clock_ring_colors[second_idx] = second_color;
            }
            // apply colors to light
            for (int i = 0; i < it.size(); i++) {
              it[i] = clock_ring_colors[i];
            }
```
I need to reupload this to the clock as I have put it back up on the wall rather than have it sitting on the desk.

**Comment by markusressel** [comment]
I think you are overcomplicating things.

If you add an offset to the `i` at the very last loop, isn't this sufficient?
Something like this:
```
// apply colors to light
for (int i = 0; i < it.size(); i++) {
  val index = (i + offset) % it.size()
  it[index] = clock_ring_colors[i];
}
```

**Comment by BlackCatPeanut** [comment]
That did work! Thanks for the nudge.

I was going to make it editable within Home Assistant but there is complications as the offset cannot be stored in flash so we'd need to read it from Home Assistant at boot...then more edge cases for offline etc... For the moment I have just added a global variable with an initial value and left it at that:

```
  - id: offset_LED_position
    type: int
    restore_value: false
    initial_value: '30' # Update value to to restore after boot as Lambda updates from HA cannot be restored from Flash

```
And then the following declared in the lambda:

`            int offset = id(offset_LED_position);`

With the final piece being your suggestion with a minor tweak:

```
            //apply colors to light
            for (int i = 0; i < it.size(); i++) {
              int index = (i + offset) % it.size();
              it[index] = clock_ring_colors[i];
            }
```
Thanks for the help to get it working. And thanks for sharing the project!
