### ISSUE TITLE
Minute and second hands fixed on 12

### ISSUE THREAD

**Issue by ornellino** [markusressel/ESPHome-Analog-Clock#9]
Hi, I just installed your configuration on my clock, with and ESP32, a 24 led ring and a 4digit 7 segment tm1637. It was previously running with an Arduino sketch. But there were often problems on ntp update. So I added to your configuration only the display tm1637. I changed the board and the led numbers. 
Now it works, but the minute led and second led are fixed on first led.
Can you help me please?
Tanks in advance
Andrea

**Comment by ornellino** [comment]
Yes, it's correct. Minute and second light on the first led.

**Comment by markusressel** [comment]
If you make these changes to the `clock.h` file, does it work?
https://github.com/markusressel/ESPHome-Analog-Clock/pull/10/files

**Comment by ornellino** [comment]
Yes, it works! Tanks a lot!
An OT question... there is a way to change via action the TM1637 intensity? I tried with lambda but ESPhome return "This option is not templatable!"

**Comment by markusressel** [comment]
Sorry, but I don't know this device. As for ESPHome, you might be able to get a hold of the object using its ID and _maybe_ modify its properties after the fact. Whether this works depends on the implementation though and I have no idea about this particular device.

You can see an example of this here:
https://github.com/markusressel/ESPHome-Analog-Clock/blob/main/esphome_neopixel_clock_effect.yaml#L131
